# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

target 'FlappyBrid' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Then'
  pod 'SwiftFormat/CLI', '0.40.4'
  
end
